import * as sdk from 'microsoft-cognitiveservices-speech-sdk';
import { TranscriptionService, ApiError } from '../types';
import { config, isAzureConfigured } from '../config/environment';

export class TranscriptionServiceImpl implements TranscriptionService {
  private speechConfig: sdk.SpeechConfig | null = null;

  constructor() {
    this.initializeAzureConfig();
  }

  private initializeAzureConfig(): void {
    if (isAzureConfigured()) {
      try {
        this.speechConfig = sdk.SpeechConfig.fromSubscription(
          config.azureSpeechKey!,
          config.azureSpeechRegion!
        );
        
        // additional properties
        this.speechConfig.speechRecognitionLanguage = 'en-US';
        this.speechConfig.outputFormat = sdk.OutputFormat.Detailed;
        
        console.log('Azure Speech Service configured successfully');
      } catch (error) {
        console.warn('Failed to configure Azure Speech Service:', error);
        this.speechConfig = null;
      }
    } else {
      console.log('ℹ️  Azure Speech Service not configured - using mock transcription');
    }
  }

//  Mock transcription service
   
  public async mockTranscribe(audioBuffer: Buffer): Promise<string> {
    console.log(`Mock transcribing audio buffer (${audioBuffer.length} bytes)`);
    
   
    await this.delay(Math.random() * 2000 + 1000); 
    
    // Generate mock transcription based on buffer size
    const transcriptions = [
      "Hello, this is a sample audio transcription generated by our mock service.",
      "Welcome to VoiceOwl, your audio transcription solution.",
      "The quick brown fox jumps over the lazy dog.",
      "Testing audio transcription functionality with mock data.",
      "This is a demonstration of the transcription service working correctly.",
      "Audio file successfully processed and transcribed using mock service."
    ];
    
    const index = audioBuffer.length % transcriptions.length;
    const mockTranscription = transcriptions[index];
    
    console.log(`Mock transcription completed: "${mockTranscription}"`);
    return mockTranscription;
  }

 // azure speech trans...
  public async azureTranscribe(audioBuffer: Buffer, language: string = 'en-US'): Promise<string> {
    if (!this.speechConfig) {
      throw this.createError(
        'Azure Speech Service not configured. Please set AZURE_SPEECH_KEY and AZURE_SPEECH_REGION environment variables.',
        503,
        'AZURE_NOT_CONFIGURED'
      );
    }

    try {
      console.log(` Azure transcribing audio buffer (${audioBuffer.length} bytes) in ${language}`);
      
     
      this.speechConfig.speechRecognitionLanguage = language;
      
      const audioConfig = this.createAudioConfigFromBuffer(audioBuffer);
      
      const recognizer = new sdk.SpeechRecognizer(this.speechConfig, audioConfig);
      
      const result = await this.performRecognition(recognizer);

      try {
        recognizer.close();
      } catch (e) {
        // Ignore close errors in test environment
      }
      try {
        audioConfig.close();
      } catch (e) {
        // Ignore close errors in test environment
      }
      
      console.log(`Azure transcription completed: "${result}"`);
      return result;
      
    } catch (error) {
      console.error('something wrong Azure transcription failed:', error);
      
      if (error instanceof Error && 'statusCode' in error) {
        throw error;
      }
      
      throw this.createError(
        `Azure transcription failed: ${error instanceof Error ? error.message : 'Unknown error'}`,
        500,
        'AZURE_TRANSCRIPTION_FAILED'
      );
    }
  }

//  
  private createAudioConfigFromBuffer(buffer: Buffer): sdk.AudioConfig {
   
    const stream = sdk.AudioInputStream.createPushStream();
    
    // Push the audio data  
    const uint8Array = new Uint8Array(buffer);
    stream.write(uint8Array.buffer);
    stream.close();
    
    return sdk.AudioConfig.fromStreamInput(stream);
  }

 
  private performRecognition(recognizer: sdk.SpeechRecognizer): Promise<string> {
    return new Promise((resolve, reject) => {
      let transcription = '';
      
      recognizer.recognized = (s, e) => {
        if (e.result.reason === sdk.ResultReason.RecognizedSpeech) {
          transcription += e.result.text + ' ';
        }
      };
      
      recognizer.sessionStopped = () => {
        recognizer.stopContinuousRecognitionAsync();
        resolve(transcription.trim() || 'No speech detected in audio');
      };
      
      recognizer.canceled = (s, e) => {
        recognizer.stopContinuousRecognitionAsync();
        
        if (e.reason === sdk.CancellationReason.Error) {
          reject(this.createError(
            `Azure Speech recognition cancelled: ${e.errorDetails}`,
            500,
            'AZURE_RECOGNITION_ERROR'
          ));
        } else {
          resolve(transcription.trim() || 'Recognition was cancelled');
        }
      };
      
      // Start recognition
      try {
        if (recognizer.startContinuousRecognitionAsync) {
          recognizer.startContinuousRecognitionAsync(
            () => {
              console.log(' Azure Speech recognition started');
            },
            (error) => {
              reject(this.createError(
                `Failed to start Azure Speech recognition: ${error}`,
                500,
                'AZURE_START_ERROR'
              ));
            }
          );
        } else {
          reject(this.createError(
            'Azure Speech SDK not properly initialized',
            500,
            'AZURE_SDK_ERROR'
          ));
        }
      } catch (sdkError) {
        reject(this.createError(
          `Azure SDK error: ${sdkError instanceof Error ? sdkError.message : 'Unknown SDK error'}`,
          500,
          'AZURE_SDK_ERROR'
        ));
      }
      
      // Set timeout 
      setTimeout(() => {
        recognizer.stopContinuousRecognitionAsync();
        if (!transcription.trim()) {
          resolve('No speech detected within timeout period');
        }
      }, 30000); 
    });
  }

// check config
  public isAzureAvailable(): boolean {
    return this.speechConfig !== null;
  }

// get supported lang..
  public getSupportedLanguages(): string[] {
    return [
      'en-US', 'en-GB', 'en-AU', 'en-CA',
      'es-ES', 'es-MX', 'fr-FR', 'fr-CA',
      'de-DE', 'it-IT', 'pt-BR', 'ja-JP',
      'ko-KR', 'zh-CN', 'zh-TW', 'ru-RU',
      'ar-SA', 'hi-IN', 'th-TH', 'nl-NL'
    ];
  }

  private delay(ms: number): Promise<void> {
    return new Promise(resolve => setTimeout(resolve, ms));
  }

  private createError(message: string, statusCode: number, code?: string): ApiError {
    const error = new Error(message) as ApiError;
    error.statusCode = statusCode;
    error.code = code;
    return error;
  }
}